### ISSUE TITLE
Cryptic "File should not exist" ?

### ISSUE THREAD

**Issue by soxofaan** [ESA-EarthCODE/open-science-catalog-validation#6]
I tried to run open-science-catalog-validation against an openEO batch job result  (STAC collection) and got this result:
```
./node_modules/.bin/open-science-catalog-validation path/to/job-results.json
Validation failed!

> open-science-catalog-validation@1.0.0-rc.4 test
> stac-node-validator --config config.json path/to/job-results.json

STAC Node Validator v2.0.0-beta.12

path/to/job-results.json
  Collection: valid
  Extensions
    eo (1.1.0): valid
    file (2.1.0): valid
    processing (1.1.0): valid
    projection (1.1.0): valid
  Custom
    1. File should not exist

Summary (1)
  Valid: 0
  Invalid: 1
  Skipped: 0
```

What does the "    1. File should not exist" mean here and how can it be fixed?

**Comment by soxofaan** [comment]
attached is actual stac file:
[job-results.json](https://github.com/user-attachments/files/17620529/job-results.json)

**Comment by m-mohr** [comment]
Hey Stefaan,

the OSC validator is meant to validate the specific structure of Open Science Catalog as provided e.g. in the repository <https://github.com/ESA-EarthCODE/open-science-catalog-metadata>. You can not validate individual files outside of this structure. So if you want to validate your file within the OSC context, you need to copy it into the correct folder within the OSC metadata structure. The message is a bit unclear, but it says exactly that. It found a file in the OSC structure that's unexpected and not meant to be there ;-) We should probably reject single files as input and throw an error instead.

**Comment by soxofaan** [comment]
thanks, that error message is indeed a lot more helpful :+1:
