### ISSUE TITLE
Schema improvements

### ISSUE THREAD

**Issue by silvester-pari** [ESA-EarthCODE/open-science-catalog-validation#7]
- [ ] format `date-time` as e.g in [collection schema](https://github.com/ESA-EarthCODE/open-science-catalog-validation/blob/85340e6ced5918537573c61b937cf55141413e49/schemas/collection.json#L128C30-L128C39) -> with `datetime-local` we could automatically render a native HTML element, but we need to investigate what this means for timezones
- [x] ~format `bounding-boxes` as in [collection schema](https://github.com/ESA-EarthCODE/open-science-catalog-validation/blob/85340e6ced5918537573c61b937cf55141413e49/schemas/collection.json#L91) -> probably needs to be moved one level "lower"~ -> https://github.com/ESA-EarthCODE/open-science-catalog-validation/commit/2492abe65603f46e64cb1dac49beb740883c6ec8

**Comment by m-mohr** [comment]
datetimes in STAC must be in UTC, so I'd try to avoid local timezones getting mixed in. Otherwise you need to compute the UTC timestamp from the local timezone after the user has entered it.
